### ISSUE TITLE
Time Slots / Day Breaks in print view

### ISSUE THREAD

**Issue by walthierer** [ASKnetCommunity/Training#156] opened 2023-12-04 17:32 UTC
Day Breaks / Time Slots destroy the Print View if they are created between the module blocks. If they are placed within the module, the print view displays correct. 

edit: 

- The Browser in this case FireFox is loading the print view faster then it generates the pages and page breaks
- in Chromium based browsers this should not be an issue, so this would be the temporarily solution [1]

Fix: add note next to the "Print" button [1] [info icon] "Currently the print view works best in Chromium based browsers."

**Comment by timmwille** [comment] 2023-12-12 16:19
here are examples where it is visible:

[Broken-Example2-ASKtraining.pdf](https://github.com/ASKnetCommunity/Training/files/13650585/Broken-Example2-ASKtraining.pdf)
[Broken-Example-ASKtraining.pdf](https://github.com/ASKnetCommunity/Training/files/13650586/Broken-Example-ASKtraining.pdf)
[Working-Example-ASKtraining.pdf](https://github.com/ASKnetCommunity/Training/files/13650587/Working-Example-ASKtraining.pdf)

**Comment by bmen** [comment] 2023-12-19 15:08
I have tried this and I cannot reproduce @timmwille problem.

I have now added a page break at Day Break. A new page begins with a day break.

**Comment by bmen** [comment] 2023-12-20 13:53
We currently seem to have the problem that the print version is not the same in all operating systems and browsers. All browsers with the Chrome engine work well, but there are problems with some Firefox browsers. For example, a day break between two modules makes a strange break and is not displayed completely.
I have no problems. Neither with Chrome engines nor with Firefox. I have a Linux Ubuntu 20.04 + Brave Version 1.58.131 Chromium: 117.0.5938.92 / Firefox 120.0.1

If you @saisilinus  have any ideas on how we could solve this, that would be great?! The latest development status is in the branch "156-time-slots-day-breaks-in-print-view". I have already merged all the changes from the Development Branch.

If we can't get the print versions to look roughly the same on the different systems, we may have to think about using a PDF converter like this one: https://github.com/parallax/jsPDF. But that would be a feature that would have to be discussed and commissioned first!

**Comment by saisilinus** [comment] 2023-12-21 10:29
I concur with @bmen. It seems that the [Window.print()](https://developer.mozilla.org/en-US/docs/Web/API/Window/print) feature is inconsistent in different environments. I've tried some of the workarounds but I can't get rid of the bug for now. The problem is with the implementation of the print feature rather than a bug on our end. It seems that printing starts immediately when you are using Firefox sometimes while it always waits for the site to load when you use Chrome. I think it's also part of the reason why the preview takes some time to load when using Chrome and almost no time at all on Mozilla.

I also noticed a related bug. Sometimes the references list is empty when you print if you open and close the list before printing.

I think we should add a disclaimer with a CanIUse list for now to the README. We should also think about a long-term solution like @bmen said. I'll try and see if there is a workaround in the meantime.

**Comment by walthierer** [comment] 2023-12-22 10:55
maybe there is hope, that the window.print() function will be improved soon?? i think a disclaimer in the README. would be good for now. what do you think @timmwille?

**Comment by timmwille** [comment] 2023-12-22 13:09
Ok so the issue is: 

- The Browser in this case FireFox is loading the print view faster then it generates the pages and page breaks
- in Chromium based browsers this should not be an issue, so this would be the temporarily solution [1]

Fix: add note next to the "Print" button [1] [info icon] "Currently the print view works best in Chromium based browsers."

**Closed** 2024-03-05 13:42 UTC
Labels: bug, prio1, waiting-for-input, ready, print
